affect:
    id: affect
    name: Test Affect
    turns: 100
    description: test
    type: BASIC
    object: Affect
    args: 
    - Null


ethereal:
    id: ethereal
    name: Ethereal
    turns: 5
    description: Immunity to physical damage, but amplified magical damage taken.
    type: BASIC
    object: AffectEthereal
    args: 
    - 1.5
    - Null


stunned:
    id: stunned
    name: Stunned
    turns: 1
    description: Cannot act during your turns!
    type: BASIC
    object: AffectStunned
    args: 
    - Null
