template:
  name: Skeleton
  stats:
    Health: 15
    Mana: 20

    Armor: 0
    Marmor: 0

    Body: 1
    Mind: 2
    Soul: 0
    
    Experience: 1

  loot:
    long sword: 1
    red potion: 0.1
    

  skills:
    swing: 3
    

  combat_loop:
    - skill: swing 
      target: enemy_random
    


skeleton:
  name: Skeleton
  stats:
    Health: 15
    Mana: 200

    Armor: 0
    Marmor: 0

    Body: 1
    Mind: 0
    Soul: 0
    
    Experience: 3

  loot:
    long sword: 1

  skills:
    magic missile: 8
    swing: 3

  combat_loop:
    - skill: swing 
      target: enemy_random
    - skill: magic missile 
      target: enemy_random

rat:
  name: Rat
  stats:
    Health: 5
    Mana: 20

    Armor: 0
    Marmor: 0

    Body: 0
    Mind: 0
    Soul: 0
    
    Experience: 1

  loot: 
    lucky charm: 1

  skills:
    swing: 70

  combat_loop:
    - skill: swing
      target: enemy_random