template:
  name: Skeleton
  stats:
    hp: 3
    mp: 20

    armor: 0
    marmor: 0

    body: 0
    mind: 0
    soul: 0
    
    exp: 2

  loot:
    long sword: 1
    red potion: 0.1
    

  skills:
    swing: 3
    

  combat_loop:
    - skill: swing 
      target: enemy_random
    


skeleton:
  name: Skeleton
  stats:
    hp: 40
    mp: 60

    armor: 4
    marmor: 0

    body: 6
    mind: 0
    soul: 0
    
    exp: 5

  loot:
    long sword: 0.1

  skills:
    swing: 75
    magic missile: 75

  combat_loop:
    - skill: magic missile 
      target: enemy_random


rat:
  name: Rat
  stats:
    hp: 3
    mp: 20

    armor: 0
    marmor: 0

    body: 0
    mind: 0
    soul: 0
    
    exp: 2

  loot: 
    lucky charm: 1

  skills:
    swing: 70

  combat_loop:
    - skill: swing
      target: enemy_random

  
tutorial rat:
  name: Rat
  stats:
    hp: 3
    mp: 20

    armor: 0
    marmor: 0

    body: 0
    mind: 0
    soul: 0
    
    exp: 2

  loot: 
    tutorial rat dagger: 1

  skills:
    swing: 1

  combat_loop:
    - skill: swing
      target: enemy_random