template:
  name: Skeleton
  stats:
    hp: 15
    mp: 20

    armor: 0
    marmor: 0

    str: 0
    dex: 0
    int: 0
    luk: 0
    
    exp: 1

  loot:
    long sword: 1
    red potion: 0.1

  skills:
    swing: 75

  combat_loop:
    - skill: swing 
      target: enemy_random


skeleton:
  name: Skeleton
  stats:
    hp: 15
    mp: 20

    armor: 0
    marmor: 0

    str: 1
    dex: 2
    int: 0
    luk: 0
    
    exp: 1

  loot:
    long sword: 1

  skills:
    swing: 75

  combat_loop:
    - skill: swing 
      target: enemy_random

rat:
  name: Rat
  stats:
    hp: 5
    mp: 20

    armor: 0
    marmor: 0

    str: 0
    dex: 0
    int: 0
    luk: 0
    
    exp: 1

  loot: 
    lucky charm: 1

  skills:
    swing: 30

  combat_loop:
    - skill: swing
      target: enemy_random