1:
  - prefix_name: 'Strong'
    stats:
      str: 1

  - prefix_name: 'Swift'
    stats:
      dex: 1

  - prefix_name: 'Smart'
    stats:
      int: 1

  - prefix_name: 'Lucky'
    stats:
      luk: 1

  - prefix_name: 'Weak'
    stats:
      str: -1

  - prefix_name: 'Slow'
    stats:
      dex: -1

  - prefix_name: 'Dumb'
    stats:
      int: -1

  - prefix_name: 'Unlucky'
    stats:
      luk: -1

