
leather helmet:
  description: A simple plain leather helmet
  equiped: false
  history: {}
  item_type: Equipment
  name: 'Leather helmet'
  requirements:
    armor: 0
    dex: 0
    hp_max: 0
    int: 0
    level: 0
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  slot: Head
  stats:
    armor: 2
    dex: 0
    hp_max: 0
    int: 0
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  tags: []

red potion:
  description: Its just a bottle of holy water mixed with tomato juice
  history: {}
  item_type: Consumable
  name: '@redRed Potion@normal'
  skills:
  - cure light wounds
  tags: []

long sword:
  description: A trusty long sword, perfection
  equiped: false
  history: {}
  item_type: Equipment
  name: Long Sword
  requirements:
    armor: 0
    dex: 0
    hp_max: 0
    int: 0
    level: 2
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  slot: Primary
  stats:
    armor: 0
    dex: 1
    hp_max: 0
    int: 0
    luk: 0
    marmor: 0
    mp_max: 0
    str: 1
  tags: []


dagger :
  description: A trusty long sword, perfection
  equiped: false
  history: {}
  item_type: Equipment
  name: Dagger
  requirements:
    armor: 0
    dex: 0
    hp_max: 0
    int: 0
    level: 1
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  slot: Primary
  stats:
    armor: 0
    dex: 1
    hp_max: 0
    int: 0
    luk: 0
    marmor: 0
    mp_max: 0
    str: 1
  tags: []

pan lid:
  description: This tiny pan lid is just big enough to act as a buckler shield
  equiped: false
  history: {}
  item_type: Equipment
  keep: false
  name: Pan Lid
  requirements:
    armor: 0
    dex: 0
    hp_max: 0
    int: 0
    level: 1
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  slot: Secondary
  stats:
    armor: 1
    dex: 0
    hp_max: 0
    int: 0
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  tags: []

sandals:
  description: Perfect for a walk, or a run from a scary monster!
  equiped: false
  history: {}
  item_type: Equipment
  keep: false
  name: Sandals
  requirements:
    armor: 0
    dex: 0
    hp_max: 0
    int: 0
    level: 0
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  slot: Feet
  stats:
    armor: 0
    dex: 1
    hp_max: 0
    int: 0
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  tags: []


lucky charm:
  description: You think this is supposed to be a rabbits foot but its so worn out
    you can't tell
  equiped: false
  history: {}
  item_type: Equipment
  keep: false
  name: Lucky Charm
  requirements:
    armor: 0
    dex: 0
    hp_max: 0
    int: 0
    level: 2
    luk: 0
    marmor: 0
    mp_max: 0
    str: 0
  slot: Trinket
  stats:
    armor: 0
    dex: 0
    hp_max: 0
    int: 0
    luk: 4
    marmor: 0
    mp_max: 0
    str: 0
  tags: []
