sword:
  description: Cool sword bro
  equiped: false
  history: {}
  item_type: Equipment
  keep: false
  name: Sword
  requirements:
    Armor: 0
    Body: 0
    Level: 3
    Marmor: 0
    Max Health: 0
    Max Mana: 0
    Mind: 0
    Soul: 0
  slot: Primary
  stats:
    Armor: 0
    Body: 2
    Marmor: 0
    Max Health: 0
    Max Mana: 0
    Mind: 0
    Soul: 1
  tags: []

lucky charm:
  description: Description here
  equiped: false
  history: {}
  item_type: Equipment
  keep: false
  name: Lucky Charm
  requirements:
    Armor: 0
    Body: 0
    Level: 3
    Marmor: 0
    Max Health: 0
    Max Mana: 0
    Mind: 0
    Soul: 0
  slot: Trinket
  stats:
    Armor: 0
    Body: 0
    Marmor: 0
    Max Health: 0
    Max Mana: 0
    Mind: 0
    Soul: 0
  tags: []

red potion:
  description: Just a bottle of cold tomato soup
  history: {}
  item_type: Consumable
  keep: false
  name: Red Potion
  skills:
  - cure light wounds
  tags: []

