
tutorial rat dagger:
  premade_id: tutorial rat dagger
  description: A dagger... what was the rat doing with a fucking dagger?
  item_type: equipment
  name: Chewed up Dagger
  requirements:
    armor: 0
    body: 0
    lvl: 1
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 0
  slot: primary
  stats:
    armor: 0
    body: 1
    marmor: 0
    hp_max: 10
    mp_max: 10
    mind: 1
    soul: 1
  tags: []

sword:
  premade_id: sword
  description: Cool sword bro
  item_type: equipment
  name: Sword

  slot: primary
  requirements:
    armor: 0
    body: 0
    lvl: 1
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 0
  stats:
    armor: 0
    body: 2
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 1
    soul: 1

lucky charm:
  premade_id: lucky charm
  description: A rabbits foot, how lucky
  item_type: equipment
  name: Lucky charm

  slot: trinket
  requirements:
    lvl: 1
    hp_max: 0
    mp_max: 0
    armor:  0
    marmor: 0
    body: 0
    mind: 0
    soul: 0
  stats:
    hp_max: 5
    mp_max: 5
    armor:  0
    marmor: 0
    body: 0
    mind: 0
    soul: 1

long sword:
  premade_id: long sword
  description: A looooooooooong sword
  item_type: equipment
  name: Longsword

  slot: primary
  requirements:
    lvl: 3
    hp_max: 0
    mp_max: 0
    body: 0
    mind: 0
    soul: 0
    armor:  0
    marmor: 0
  stats:
    hp_max: 0
    mp_max: 0
    body: 3
    mind: 0
    soul: 0
    armor:  0
    marmor: 0

whip:
  premade_id: whip
  description: Now watch me.. you know..
  item_type: equipment
  name: Whip

  slot: secondary
  requirements:
    lvl: 5
    hp_max: 0
    mp_max: 0
    body: 0
    mind: 0
    soul: 0
    armor:  0
    marmor: 0
  stats:
    hp_max: 0
    mp_max: 10
    body: 0
    mind: 0
    soul: 3
    armor:  0
    marmor: 0

red potion:
  premade_id: red potion
  description: Just a bottle of cold tomato soup
  item_type: consumable
  name: Red Potion
  use_perspectives: potion0
  skills:
  - regen_hp30

blue potion:
  premade_id: blue potion
  description: Just a bottle of REALLY cold tomato soup
  item_type: consumable
  name: Blue Potion
  use_perspectives: potion0
  skills:
  - regen_mp30

translucent scroll:
  premade_id: translucent scroll
  description: Its so hard to read...
  item_type: consumable
  name: Translucent scroll
  use_perspectives: scroll0
  skills:
  - ethereal

rock:
  premade_id: rock
  item_type: misc
  name: Rock
  description: Just a rock
  
