
tutorial rat dagger:
  description: A dagger... what was the rat doing with a fucking dagger?
  equiped: false
  history: {}
  item_type: equipment
  keep: false
  name: Dagger
  requirements:
    armor: 0
    body: 0
    lvl: 1
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 0
  slot: primary
  stats:
    armor: 0
    body: 1
    marmor: 0
    hp_max: 10
    mp_max: 10
    mind: 1
    soul: 1
  tags: []

sword:
  description: Cool sword bro
  equiped: false
  history: {}
  item_type: equipment
  keep: false
  name: Sword
  requirements:
    armor: 0
    body: 0
    lvl: 3
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 0
  slot: primary
  stats:
    armor: 0
    body: 2
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 1
  tags: []

lucky charm:
  description: Description here
  equiped: false
  history: {}
  item_type: equipment
  keep: false
  name: Lucky Charm
  requirements:
    armor: 0
    body: 0
    lvl: 3
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 2
  slot: trinket
  stats:
    armor: 0
    body: 0
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 0
  tags: []

red potion:
  description: Just a bottle of cold tomato soup
  history: {}
  item_type: consumable
  keep: false
  name: Red Potion
  skills:
  - cure light wounds
  tags: []

long sword:
  description: Cool sword bro
  equiped: false
  history: {}
  item_type: equipment
  keep: false
  name: Sword
  requirements:
    armor: 0
    body: 0
    lvl: 3
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 0
  slot: primary
  stats:
    armor: 0
    body: 2
    marmor: 0
    hp_max: 0
    mp_max: 0
    mind: 0
    soul: 1
  tags: []