
swing:
  name: Swing
  description: Swing at your target dealing 1 physical damage + 70% of strength and 100% dexterity
  level: 0 
  must_be_fighting: True
  target_self_is_valid: True
  target_others_is_valid: True
  hp_cost: 0
  mp_cost: 0
  script_to_run:
    name_of_script: skill_simple_damage
    arguments: [1, 'physical', {'str': 0.7, 'dex': 1}] 

  use_perspectives:
    you on you:           'You swing and hit yourself!'
    you on other:         'You swing and hit #OTHER#'
    user on user:         '#USER# swings and hits themselves!'
    user on you:          '#USER# swings and hits you!'
    user on other:        '#USER# swings and hits #OTHER#'

    you on you fail:      'You lose your footing while swinging at yourself!'
    you on other fail:    'You lose your footing while swinging at #OTHER#'
    user on user fail:    '#USER# loses their footing while swinging at themselves'
    user on you fail:     '#USER# loses their footing while swinging at you!'
    user on other fail:   '#USER# loses their footing while swinging at #OTHER#'


  
magic missile:
  name: Magic Missile
  description: Fire a magic missile at your target dealing 2 magical damage + 100% of your ingelligence
  level: 0
  must_be_fighting: True
  target_self_is_valid: True
  target_others_is_valid: True
  hp_cost: 0
  mp_cost: 2
  script_to_run:
    name_of_script: skill_simple_damage
    arguments: [2, 'magical', {'int': 1}]

  use_perspectives:
    you on you:           'You point at yourself and fire a magical missile straight to your forehead!'
    you on other:         'You point at #OTHER# and fire a magical missile into their chest!'
    user on user:         '#USER# points at themselves and fires a magical missile straight into their forehead!'
    user on you:          '#USER# points at you and fires a magical missile straight into your chest!'
    user on other:        '#USER# points at #OTHER# and fires a magical missile straight into their chest!'

    you on you fail:      'You lose your concentration while gathering energy to shoot yourself in the face'
    you on other fail:    'You lose your concentration while gathering energy to fire a magical missile at #OTHER#'
    user on user fail:    '#USER# loses their concentration while gathering energy to fire a magical missile at themselves?'
    user on you fail:     '#USER# loses their concentration while attempting to fire a magical missile at you'
    user on other fail:   '#USER# loses their concentration while attempting to fire a magical missile at #OTHER#'

brain sap:
  name: Give head
  description: hoo hoo hee haa
  level: 2
  must_be_fighting: True
  target_self_is_valid: False
  target_others_is_valid: True
  hp_cost: 0
  mp_cost: 2
  script_to_run:
    name_of_script: skill_simple_damage
    arguments: [2, 'pure', []]

  use_perspectives:
    you on you:           'You swing and hit yourself!'
    you on other:         'You swing and hit #OTHER#'
    user on user:         '#USER# swings and hits themselves!'
    user on you:          '#USER# swings and hits you!'
    user on other:        '#USER# swings and hits #OTHER#'

    you on you fail:      'You lose your footing while swinging at yourself!'
    you on other fail:    'You lose your footing while swinging at #OTHER#'
    user on user fail:    '#USER# loses their footing while swinging at themselves'
    user on you fail:     '#USER# loses their footing while swinging at you!'
    user on other fail:   '#USER# loses their footing while swinging at #OTHER#'

cure light wounds:
  name: Cure Light Wounds
  description: Heal your target for 10 + 100% intelligence
  level: 0
  must_be_fighting: False
  target_self_is_valid: True
  target_others_is_valid: True
  hp_cost: 0
  mp_cost: 2
  script_to_run:
    name_of_script: skill_simple_damage
    arguments: [10, 'heal', {'int': 1}]

  use_perspectives:
    you on you:           'You pray for yourself'
    you on other:         'You pray for #OTHER#'
    user on user:         '#USER# prays for themselves'
    user on you:          '#USER# prays for you'
    user on other:        '#USER# prays for #OTHER#'

    you on you fail:      'You lose concentration while praying for yourself'
    you on other fail:    'You lose concentration while praying for #OTHER#'
    user on user fail:    '#USER# loses their concentration while praying for themselves'
    user on you fail:     '#USER# loses their concentration while praying for you'
    user on other fail:   '#USER# loses their concentration while praying for #OTHER#'

ethereal:
  name: Become Ethereal
  description: You become ethereal
  level: 0
  must_be_fighting: False
  target_self_is_valid: True
  target_others_is_valid: False
  hp_cost: 0
  mp_cost: 2
  script_to_run:
    name_of_script: skill_set_afflictions
    arguments: ['ethereal']

  use_perspectives:
    you on you:           'You focus, and begin to fade'
    you on other:         'You focus, and #OTHER# begins to fade'
    user on user:         '#USER# focuses, and begins to fade'
    user on you:          '#USER# focuses, and you begin to fade'
    user on other:        '#USER# focuses, and #OTHER# begins to fade'

    you on you fail:      'You lose your focus'
    you on other fail:    'You lose your focus on #OTHER#'
    user on user fail:    '#USER# loses their focus'
    user on you fail:     '#USER# loses their focus on you'
    user on other fail:   '#USER# loses their focus on #OTHER#'

bash:
  name: Bash
  description: Bash your target, stunning them for 1 turn
  level: 0
  must_be_fighting: True
  target_self_is_valid: False
  target_others_is_valid: True
  hp_cost: 0
  mp_cost: 0
  script_to_run:
    name_of_script: skill_simple_damage_and_affliction
    arguments: [0, 'physical', {'str': 1}, 'stunned']

  use_perspectives:
    you on you:           'You bash yourself'
    you on other:         'You bash #OTHER#'
    user on user:         '#USER# bashes themselves'
    user on you:          '#USER# bashes you'
    user on other:        '#USER# bashes #OTHER#'

    you on you fail:      'You fail to bash yourself'
    you on other fail:    'You fail to bash #OTHER#'
    user on user fail:    '#USER# fails to bash themselves'
    user on you fail:     '#USER# fails to bash you'
    user on other fail:   '#USER# fails to bash #OTHER#'

  