world:
  loading:
    name: bruh
    description: BRUH
    exits: []
    
  tutorial:
    name: Abyss
    description: "
    Welcome. You may go east for a quick tutorial\n
    Or go west if you know what you are doing\n
    Use the \"go\" command, for example:\n
    \"go east\""
    exits: 
      east: home
      west: home
    instanced: True

  home:
    name: Kerning City
    description: "
    You find yourself in the dimly lit streets of Kerning City.\n
    A sprawling urban jungle. Neon signs flicker and hum.\n
    Shadows dance along the graffiti covered walls of grimy brick buildings."
    exits: 
      north: kerning_road_to_construction


  kerning_road_to_construction:
    name: The road by a construction site
    description: "
    Piles of discarded machinery and rusted barrels line the road.\n
    The hum of distant power tools and the occasional clang of metal echo faintly.\n
    A large skeletal framework of a construction site is here.
    "
    exits:
      north: kerning_dark_alley
      south: home
      inside the construction site: kerning_construction
    enemies:
      - shroom
      - shroom

  ###
  kerning_dark_alley:
    name: Dark Alleyway Behind the Construction
    description: "
    The alley is dark and narrow, a faint stench of oil and decay hangs in the air.\n
    Broken crates and discarded tools clutter the ground.
    "
    exits:
      south: kerning_road_to_construction
      north: kerning_dark_alley1
      east: kerning_dark_alley3
    enemies:
      - orange mushroom
  kerning_dark_alley1:
    name: Dark Alleyway Behind the Construction 1
    description: "
    The alley is dark and narrow, a faint stench of oil and decay hangs in the air.\n
    Broken crates and discarded tools clutter the ground.
    "
    exits:
      south: kerning_dark_alley
      east: kerning_dark_alley2
    enemies:
      - orange mushroom
  kerning_dark_alley2:
    name: Dark Alleyway Behind the Construction 2
    description: "
    The alley is dark and narrow, a faint stench of oil and decay hangs in the air.\n
    Broken crates and discarded tools clutter the ground.
    "
    exits:
      west: kerning_dark_alley1
      south: kerning_dark_alley3
    enemies:
      - blue mushroom
  kerning_dark_alley3:
    name: Dark Alleyway Behind the Construction 3
    description: "
    The alley is dark and narrow, a faint stench of oil and decay hangs in the air.\n
    Broken crates and discarded tools clutter the ground.
    "
    exits:
      north: kerning_dark_alley2
      west: kerning_dark_alley
    enemies:
      - orange mushroom
  ###


  ###
  kerning_construction:
    name: Inside the construction site
    description: "
    A chaotic maze of half finished steel scaffolding.\n
    Piles of concrete rubble and rusted bolts litters the floor.\n
    Wooden beams are used to close the gaping holes between the floors.
    "
    exits:
      outside: kerning_road_to_construction
      upwards: kerning_construction_hidden
      west: kerning_construction1
      east: kerning_construction2
    enemies:
      - orange mushroom

  kerning_construction1:
    name: Inside the construction site 1
    description: "
    A chaotic maze of half finished steel scaffolding.\n
    Piles of concrete rubble rusted bolts litters the floor.\n
    Wooden beams are used to close the gaping holes between the floors.
    "
    exits:
      east: kerning_construction
      west: kerning_construction2
    enemies:
      - orange mushroom

  kerning_construction2:
    name: Inside the construction site 2
    description: "
    A chaotic maze of half finished steel scaffolding.\n
    Piles of concrete rubble rusted bolts litters the floor.\n
    Wooden beams are used to close the gaping holes between the floors.
    "
    exits:
      east: kerning_construction1
      west: kerning_construction
    enemies:
      - blue mushroom
  ###


  ###
  kerning_construction_hidden:
    name: The top of the construction site
    description: "
    You reach the top floor of the construction site.\n
    Perched high above the abondoned chaos below.\n
    The night sky stretches endlessly above, you can see the city in the distance.\n
    In the vertical distance...
    "
    exits:
      downwards: kerning_construction
      jump: home

    enemies:
      - octopus

  ###
      



    